series/urls.py
from django.conf.urls import url 

from .views import (
		SeriesListView,
		SeriesDetailView,
		SeriesCreateView,
		SeriesUpdateView,
		SeriesDeleteView,
		EpisodeDetailView
	)

urlpatterns = [
	url(r'^$', SeriesListView.as_view(), name='list'),
	url(r'^create/$', SeriesCreateView.as_view(), name='create'),
	url(r'^(?P<slug>[\w-]+)/$', SeriesDetailView.as_view(), name='detail'),
	url(r'^(?P<se_slug>[\w-]+)/(?P<ep_slug>[\w-]+)/$', EpisodeDetailView.as_view(), name='episode_detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$', SeriesUpdateView.as_view(), name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$', SeriesDeleteView.as_view(), name='delete'),
]

woran/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from django.conf import settings
from django.conf.urls.static import static

# from django.views.generic import TemplateView home, video_detail, category_detail,

from .views import HomeView
# from videos.views import VideoListView, VideoDetailView, VideoCreateView, VideoUpdateView, VideoDeleteView
from comments.views import comment_thread, comment_create_view
from notifications.views import all, read, get_notifications_ajax
from billing.views import upgrade, billing_history, cancel_subscription
from django.views.generic import TemplateView
from accounts.views import account_home




urlpatterns = [
    url(r'^babs/admin/', admin.site.urls),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^series/', include('series.urls', namespace='series')),
    url(r'^videos/', include('videos.urls', namespace='videos')),

    # url(r'^home/$', TemplateView.as_view(template_name="home.html"), name='home'),

    url(r'^contact/$', TemplateView.as_view(template_name='company/contact_us.html'), name='contact_us'),
    # url(r'^$', home, name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    # url(r'^videos/$', category_list, name='category_list'),
    # url(r'^videos/(?P<cat_slug>[\w-]+)/$', category_detail, name='category_detail'),
    
    # url(r'^videos/(?P<cat_slug>[\w-]+)/(?P<vid_slug>[\w-]+)/$', video_detail, name='video_detail'),
    
    url(r'^comment/create/$', comment_create_view, name='comment_create'),
    url(r'^comment/(?P<id>\d+)/$', comment_thread, name='comment_thread'),
    url(r'^notifications/$', all, name='notifications_all'),
    url(r'^notifications/ajax/$', get_notifications_ajax, name='get_notifications_ajax'),
    url(r'^notifications/read/(?P<id>\d+)/$', read, name='notifications_read'),
    url(r'^upgrade/$', upgrade, name='account_upgrade'),
    url(r'^billing/$', billing_history, name='billing_history'),
    url(r'^billing/cancel$', cancel_subscription, name='cancel_subscription'),
    url(r'^account/$', account_home, name='account_home'),
    url(r'^accounts/', include('allauth.urls')),
]




if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account_home.html
{% extends 'base.html' %}





{% block content %}

<div style="padding-top: 150px;"></div>
<div class="main main-raised" style="padding-bottom: 180px;">
  <div class="container">

  <div class="row" style="padding-top: 110px;">
  	<div class="col-sm-8 col-sm-offset-2">
  		<h2>Account</h2>
  		<hr>
  	</div>
  </div>
  <div class="row">
  	<div class="col-sm-8 col-sm-offset-2">
  		<h3>Notifications <small> <a href="{% url 'notifications_all' %}">View All</a></small></h3>

  		<table class="table" style="margin-top: 20px;">
			{% for note in notifications %}
			<tr>
				<td>{{ note|safe }}</td>
				<td>{% if note.read %}Read{% else %}Unread{% endif %}</td>
			</tr>
			{% endfor %}	
		</table>

  	</div>
  </div>

  <div class="row">
  <div class="col-sm-8 col-sm-offset-2">
	  <h3>Account Options</h3>
	  <p class="lead">
	  {% if request.user.is_member %}
	  	Subscription active until: <b>{{ request.user.membership.date_end }}</b>
	  {% endif %}	
	  </p>

	  {% if request.user.is_member and request.user.usermerchantid.subscription_id %}
	  
	  <a href="{% url 'cancel_subscription' %}"> Cancel Subscription </a>

	  {% elif not request.user.is_member %}

	  <a href="{% url 'account_upgrade' %}">Upgrade</a> <p> to get unlimited access</p>

	  {% else %}



	  {% endif %}

	  <h3>Recent Billing History<small><a href="{% url 'billing_history' %}"> View All</a></small></h3>
	  <table class="table">
	        <thead>
	            <th>Order#</th>
	            <th>Amount</th>
	            <th>Payment Method</th>
	            <th>Date</th>
	        </thead>
	            {% for object in transactions %}
	                <tr>
	                    <td>{{ object.order_id }}</td>
	                    <td>{{ object.amount }}</td>
	                    <td>{{ object.card_type }}{% if object.last_four %}<br>Last Four Digits: {{ object.last_four }}{% endif %}</td>
	                    <td>{{ object.timestamp }}</td>
	                </tr>
	            {% endfor %}
	   </table>
 		 </div>
  	  </div> 
  </div>
</div>


{% endblock %}

templates/base.html
{% load static %}
{% load search_form %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>{% block title %}Woran{% endblock %}</title>

    <!-- Meta OG -->
    <meta property="og:title" content="Woran">
    <meta property="og:description" content="Bringing you the best of African entertainment in the diaspora and beyond">
    <meta property="og:image" content="{% static 'img/logo/logo2.png' %}">
    <meta property="og:url" content="http://www.woran.com/">
    <meta property="og:site_name" content="Woran">
    <!-- /Meta OG -->

    <!-- Twitter Card -->
    <meta name="twitter:card" content="Woran">
    <meta name="twitter:description" content="Bringing you the best of African entertainment in the diaspora and beyond">
    <meta name="twitter:title" content="Woran">
    <meta name="twitter:site" content="http://www.woran.com/">
    <meta name="twitter:image" content="{% static 'img/logo/logo2.png' %}">
    <meta name="twitter:creator" content="@ibroCEO">

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />

    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/material-kit.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/demo.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>

    <style>{% block style %}{% endblock %}</style>

</head>

<body class="landing-page">
    
    {% include 'navbar.html' %}

    <div class="wrapper">
        <div class="container">
        <!-- <div id="notificationsLoader" style="padding-top: 80px">   
        </div> -->
        {% if messages %}
            <div class="messages" style="padding-top: 80px;">
            <!-- <div class="alert alert-success"> -->
                {% for message in messages %}
                    <div class="container-fluid">
                        <div class="alert {% if 'error' in message.tags %}alert-warning{%else%}alert-success{% endif %}" role="alert">{{ message }}</div>
                          <!--   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true"><i class="material-icons">clear</i></span>
                            </button> -->
                    </div>
                {% endfor %}
            <!-- </div> -->
            </div>
            {% endif %}
        </div>


        <!-- <div style="min-height: 950px;"></div> -->
        <main style="min-height: 950px;">{% block content %}{% endblock %}</main>

        <footer class="footer">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="/">
                                Woran
                            </a>
                        </li>
                        <li>
                            <a href="">
                               About Us
                            </a>
                        </li>
                        <li>
                            <a href="">
                               Blog
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <!-- Licenses -->
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    &copy; 2017, created by ibrokola
                </div>
            </div>
        </footer>

    </div>
</body>
    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/material.min.js' %}"></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{% static 'js/nouislider.min.js' %}" type="text/javascript"></script>

    <!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
    <script src="{% static 'js/bootstrap-datepicker.js' %}" type="text/javascript"></script>

    <!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
    <script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>

    <script src="https://js.braintreegateway.com/js/braintree-2.32.1.min.js"></script>

    <script>
        $(document).ready(function(){
            // alert('Working')
            {% block jquery %}

            {% endblock %}
        });
    </script>
    <script>
        $(document).ready(function(){
            $(".notification-toggle").click(function(e){
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "{% url 'get_notifications_ajax' %}",
                    data:{
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                    },
                    success: function(data){
                        $("#notification_dropdown").html('<li class="dropdown-header"></li>');
                        var count = data.count
                        //console.log(count)
                        if (count == 0){
                            var url = "{% url 'notifications_all' %}"
                            $("#notification_dropdown").append("<li><a href='" + url + "'>View All Notifications</a></li>")
                        } else{
                        $(data.notifications).each(function(){
                            var link = this;
                            $("#notification_dropdown").append("<li>" + link + "</li>")
                        })
                        }
                        console.log(data.notifications);
                    },
                    error: function(rs, e){
                        console.log(rs);
                        console.log(e);
                    }
                })
            })
        })
    </script>

</html>

templates/base_allauth.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
	<li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Welcome to | {% endblock %}

{% load i18n %}

{% load crispy_forms_tags %}

{% load account socialaccount %}

{% block content %}

<div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="title">Welcome to Woran.</h1>
                    <h4>Bringing you the best of African Entertainment in the diaspora.</h4>
                    <br />
                    <a href="" class="btn btn-danger btn-raised btn-lg">
                        <i class="fa fa-play"></i> Watch video
                    </a>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-xl-6 col-xl-offset-0">
                              <!-- Nav tabs -->
                
                              <ul class="nav nav-tabs justify-content-center" role="tablist">
                                <li role="presentation" class="active"><a href="#register" aria-controls="register" role="tab" data-toggle="tab">Register</a></li>
                                <li role="presentation"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">Login</a></li>
                              </ul>

                              <!-- Tab panes -->
                              <div class="card-block">
                              <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="register">
                                    <br>
                                    <div class="panel panel-default">
                                    {# load socialaccount #}
                                      <div class="panel-body">
                                        <a href="{# provider_login_url 'facebook' method='oauth2' #}" class='btn-floating btn-lg btn-fb'><i class="fa fa-facebook"></i></a>
                                        <a href="{# provider_login_url 'twitter' #}" class='btn-floating btn-small btn-tw'><i class="fa fa-twitter"></i></a>
                                        <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">{% csrf_token %}
                                        {{ signup_form|crispy }}
                                        <input type="submit" class="btn btn-primary btn-block" value='Get free account'>
                                        </form>
                                      </div>
                                    </div>      
                                </div>
                                <div role="tabpanel" class="tab-pane" id="login">
                                <br>
                                    <div class="panel panel-default">
                                      <div class="panel-body">
                                      {# load socialaccount #}
                                        <a href="{# provider_login_url 'facebook' method='oauth2' #}" class='btn-floating btn-small btn-fb'><i class="fa fa-facebook"></i></a>
                                        <a href="{# provider_login_url 'twitter' #}" class='btn-floating btn-small btn-tw'><i class="fa fa-twitter"></i></a>
                                        <form class="signup" id="signup_form" method="post" action="{% url 'account_login' %}">{% csrf_token %}
                                            {{ login_form|crispy }}
                                            <input type="submit" class="btn btn-primary btn-raise btn-block" value='Login'>
                                        </form>
                                        </div>
                                       </div> 
                                    </div>
                              </div>
                            
                        </div>
                      </div>  
                    </div>
                </div>
            </div>
        </div>
</div>

    <div class="main main-raised">
        <div class="container">
            <div class="section text-center section-landing">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h2 class="title">Your favourite videos</h2>
                        <!-- <h5 class="description">{{ videos }}</h5> -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <!-- <div class="row"> -->
                        {% for vid in videos %}
                            <div class="col-md-3">
                                <p>{{ vid.embed_code|safe }}</p>
                                <!-- <br> -->
                                <a href="{{ vid.get_absolute_url }}">{{ vid.title }}</a>  
                            </div>
                        {% endfor %}
                        <!-- </div> -->
                        <!-- <p> {{ video_embed|safe }} </p> -->
                    </div>
                </div>
                <div class="row">
                    <!-- <div class="col-md-4">
                        <div class="card card-signup">
                            <div class="input-group">
                                {# include "account/signup_and_login.html" with form=form #}
                            </div>
                        </div>
                    </div> -->
                </div>

<!--                <div class="features">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="info">
                                <div class="icon icon-primary">
                                    <i class="material-icons">chat</i>
                                </div>
                                <h4 class="info-title">First Feature</h4>
                                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="info">
                                <div class="icon icon-success">
                                    <i class="material-icons">verified_user</i>
                                </div>
                                <h4 class="info-title">Second Feature</h4>
                                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="info">
                                <div class="icon icon-danger">
                                    <i class="material-icons">fingerprint</i>
                                </div>
                                <h4 class="info-title">Third Feature</h4>
                                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                            </div>
                        </div>
                    </div>
                </div> -->
            </div>

            <!-- <div class="section text-center">
                <h2 class="title">Here is our team</h2>

                <div class="team">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="team-player">
                                <img src="../assets/img/avatar.jpg" alt="Thumbnail Image" class="img-raised img-circle">
                                <h4 class="title">Gigi Hadid <br />
                                    <small class="text-muted">Model</small>
                                </h4>
                                <p class="description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some <a href="#">links</a> for people to be able to follow them outside the site.</p>
                                <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-twitter"></i></a>
                                <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-instagram"></i></a>
                                <a href="#pablo" class="btn btn-simple btn-just-icon btn-default"><i class="fa fa-facebook-square"></i></a>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="team-player">
                                <img src="../assets/img/christian.jpg" alt="Thumbnail Image" class="img-raised img-circle">
                                <h4 class="title">Christian Louboutin<br />
                                    <small class="text-muted">Designer</small>
                                </h4>
                                <p class="description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some <a href="#">links</a> for people to be able to follow them outside the site.</p>
                                <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-twitter"></i></a>
                                <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="team-player">
                                <img src="../assets/img/kendall.jpg" alt="Thumbnail Image" class="img-raised img-circle">
                                <h4 class="title">Kendall Jenner<br />
                                    <small class="text-muted">Model</small>
                                </h4>
                                <p>You can write here details about one of your team members. You can give more details about what they do. Feel free to add some <a href="#">links</a> for people to be able to follow them outside the site.</p>
                                <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-google-plus"></i></a>
                                <a href="#pablo" class="btn btn-simple btn-just-icon"><i class="fa fa-youtube-play"></i></a>
                                <a href="#pablo" class="btn btn-simple btn-just-icon btn-default"><i class="fa fa-twitter"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
-->

<!--                 <div class="section landing-section">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h2 class="text-center title">Work with us</h2>
                        <h4 class="text-center description">Divide details about your product or agency work into parts. Write a few lines about each one and contact us about any further collaboration. We will responde get back to you in a couple of hours.</h4>
                        <form class="contact-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Your Name</label>
                                        <input type="email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Your Email</label>
                                        <input type="email" class="form-control">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group label-floating">
                                <label class="control-label">Your Messge</label>
                                <textarea class="form-control" rows="4"></textarea>
                            </div>

                            <div class="row">
                                <div class="col-md-4 col-md-offset-4 text-center">
                                    <button class="btn btn-primary btn-raised">
                                        Send Message
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div> -->
        </div>

    </div>
{% endblock %}

templates/navbar.html
{% load static %}
{% load search_form %}
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <h5 style="font-family: 'Monoton', cursive;"><img src="{% static 'img/logo.png' %}" class="d-inline-block align-top" width="60" height="50" alt="Woran">Woran</h5>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-example">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <!-- <a href="">
                        Free Videos
                    </a> -->
                </li>
                <!-- <li>
                    <a href="{# url 'category_list' #}">
                        Movies
                    </a>
                </li> -->
<!--                 <li>
                    <a href="" target="_blank" class="btn btn-simple btn-white btn-just-icon">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="" target="_blank" class="btn btn-simple btn-white btn-just-icon">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                </li>
                <li>
                    <a href="" target="_blank" class="btn btn-simple btn-white btn-just-icon">
                        <i class="fa fa-instagram"></i>
                    </a>
                </li> -->
                {% if request.user.is_authenticated %}
                <li>
                    {% search_form request %}
                </li>
                <li>
                    <a href="">
                        {{ user }}
                    </a>
                </li>
                <li>
                    <a class="" href="{% url 'series:list' %}">Tv - Series/Movies</a>
                </li>
                <li>
                    <a class="" href="{% url 'categories:list' %}">Categories</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle notification-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true"><i class="material-icons">add_alert</i></span></a>
                  <!-- <span class="caret"></span> -->
                  <ul class="dropdown-menu" id='notification_dropdown'>
                  </ul>
                </li>
                <li>
                    <a href="{% url 'account_upgrade' %}">
                        <i class="material-icons">unarchive</i> Upgrade
                    </a>
                </li>
                <li>
                    <a class="" href="{% url 'account_home' %}">Account</a>
                </li>
                 <li>
                    <a href="{% url 'account_logout' %}">
                        Logout
                    </a>
                </li>
                {% else %}
                    {% if request.get_full_path == "/" %}
                    {% else %}
                     <li>
                        <a href="{% url 'account_login' %}">
                            Login
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'account_signup' %}">
                            Register
                        </a>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>